# Write your MySQL query statement below
SELECT DISTINCT(USER_ID) as buyer_id, 
join_date, 
SUM(CASE WHEN (ORDER_DATE >= '2019-01-01'AND ORDER_DATE <= '2019-12-31') THEN 1
ELSE 0 END) AS orders_in_2019
-- SELECT *
FROM USERS
LEFT JOIN ORDERS 
ON USERS.USER_ID = ORDERS.BUYER_ID
-- WHERE ORDER_DATE IS NULL 
-- OR (ORDER_DATE >= '2019-01-01'
-- AND ORDER_DATE <= '2019-12-31')
GROUP BY USER_ID


