# Write your MySQL query statement below
SELECT P.PRODUCT_ID, P.PRODUCT_NAME
FROM SALES S INNER JOIN PRODUCT P
ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY S.PRODUCT_ID
HAVING MIN(SALE_DATE) >= '2019-01-01' 
AND MAX(SALE_DATE) <= '2019-03-31';