# Write your MySQL query statement below
SELECT NAME, T.BALANCE
FROM USERS JOIN (SELECT ACCOUNT, SUM(AMOUNT) AS BALANCE
FROM TRANSACTIONS 
GROUP BY ACCOUNT
HAVING SUM(AMOUNT) > 10000)T ON USERS.ACCOUNT = T.ACCOUNT;