# Write your MySQL query statement below
SELECT DISTINCT(SALESPERSON.NAME)
FROM SALESPERSON 
WHERE SALESPERSON.SALES_ID NOT IN (
SELECT ORDERS.SALES_ID 
FROM ORDERS 
JOIN COMPANY
ON COMPANY.COM_ID = ORDERS.COM_ID 
WHERE COMPANY.NAME = "RED")