# Write your MySQL query statement below
SELECT USER_ID, TIME_STAMP as LAST_STAMP FROM LOGINS
WHERE TIME_STAMP IN (
    SELECT MAX(TIME_STAMP) FROM LOGINS
    WHERE TIME_STAMP LIKE '2020%'   
    GROUP BY USER_ID
);