# Write your MySQL query statement below
SELECT REQUEST_AT AS "Day", ROUND(SUM( STATUS LIKE "%cancelled%")/COUNT(STATUS), 2) AS "Cancellation Rate"
FROM TRIPS
WHERE 
REQUEST_AT BETWEEN '2013-10-01' AND '2013-10-03'
AND CLIENT_ID NOT IN
(SELECT USERS_ID FROM USERS WHERE BANNED = "Yes")
AND DRIVER_ID NOT IN
(SELECT USERS_ID FROM USERS WHERE BANNED = "Yes")
GROUP BY DAY;